apiVersion: apps/v1
kind: Deployment
metadata:
    name: users-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: users
    template:
        metadata:
            labels:
                app: users
        spec:
            containers:
                - name: users
                  image: konstantink1/kub-demo-users:latest
                  env:
                      - name: AUTH_ADDRESS
                        value: '10.102.198.197'
